function writeVariableConfig(fullFilePath, inputTable, outputTable)
% WRITEVARIABLECONFIG Create XML definition of the variable exchange for the BCVTB protocol.
%Create a XML file ("variables.cfg") with input/output configuration to be
%used by the BCVTB protocol on both sides of the communication socket. 
%
%  Syntax: writeVariableConfig(fullFilePath, inputTable, outputTable)
%
%  Inputs:
%   fullFilePath - A path to write the configuration to. 
%     inputTable - Table containing specification of the inputs to
%                  EnergyPlus.
%    outputTable - Table containing specification of the outputs from
%                  EnergyPlus.
%
%   See also: MLEP.PARSEVARIABLESCONFIGFILE, MLEP.MAKEVARIABLESCONFIGFILE
%
% (C) 2015, Willy Bernal (Willy.BernalHeredia@nrel.gov)
%     2018, Jiri Dostal (jiri.dostal@cvut.cz)
% All rights reserved. Usage must follow the license given in the class
% definition.

% XML header
docType = com.mathworks.xml.XMLUtils.createDocumentType('SYSTEM', [],'variables.dtd');
docNode = com.mathworks.xml.XMLUtils.createDocument([], 'BCVTB-variables', docType);
setEncoding(docNode, 'ISO-8859-1');
setVersion(docNode, '1.0')

% Disclaimer
disclaimer = docNode.createComment([newline, ...
    '|===========================================================|' newline,...
    '|           THIS FILE IS AUTOMATICALLY GENERATED            |' newline,...
    '| DO NOT EDIT THIS FILE AS ANY CHANGES WILL BE OVERWRITTEN! |' newline,...
    '|===========================================================|' newline,...
    ]);

% INPUT to E+
docRootNode = docNode.getDocumentElement;
insertBefore(docNode, disclaimer, docRootNode);
%docRootNode.setAttribute('SYSTEM','variables.dtd');
appendChild(docRootNode, docNode.createComment('INPUT to E+'));

table = inputTable;
names = table.Name;
types = table.Type;
for i=1:height(inputTable)
    
    %Example: <variable source="Ptolemy">
    thisElement = createElement(docNode, 'variable');
    setAttribute(thisElement, 'source','Ptolemy');
    
    %Example: <EnergyPlus schedule="TSetHea"/>
    newElement = createElement(docNode, 'EnergyPlus');
    setAttribute(newElement, names(i),... % schedule, actuator, variable
                             types(i));   % particular name
    
    appendChild(thisElement, newElement);
    appendChild(docRootNode, thisElement);
end

% OUTPUT from E+
docRootNode.appendChild(docNode.createComment('OUTPUT from E+'));
table = outputTable;
names = table.Name;
types = table.Type;
for i=1:height(outputTable)
    
    %Example: <variable source="EnergyPlus">
    thisElement = createElement(docNode, 'variable');
    setAttribute(thisElement, 'source','EnergyPlus');
    
    %Example: <EnergyPlus name="ZSF1" type="Zone Air Temperature"/>
    newElement = createElement(docNode, 'EnergyPlus');
    setAttribute(newElement, 'name',names(i)); % key value ('zone name')
    setAttribute(newElement, 'type',types(i)); % variable name ('signal')
    
    appendChild(thisElement, newElement);
    appendChild(docRootNode, thisElement);
end

xmlwrite_r18a(fullFilePath,docNode);
end